### ISSUE TITLE
master

### ISSUE THREAD

**Issue by haniju** [animaux-du-futur/chimere#1]
- [ ] popup intro avec les infos + un bouton "RANDOM chimere"
- [ ] En haut à droite ; 3 gros boutons/picto "RANDOM" "REFRESH" "INFO" 
- [x] Un exemplaire de chaque élément apparait en position pré-réglée (oeuil1 en haut à gauche, oeuil2 en haut milieu...)
- [ ] Quand je survole un des éléments avec le curseur, celui-ci change de forme avec un picto "déplacer" - si je clique et maintien je peux déplacer l'image
- [x] Quand je survole un des éléments avec le curseur, un bouton "modifier" apparait. Si je clique, une mosaïque d'images apparaît avec les autres éléments de la famille que je peux sélectionner

**Comment by haniju** [comment]
Il faut réfléchir à nouveau à comment calculer et définir les positions des éléments de manière responsive ? Actuellement on utilise les px, pour du responsive on aurait besoin de % ou de vw/vh...

**Comment by edensor** [comment]
On peut se poser aussi la question pour les dimensions des éléments.

**Comment by edensor** [comment]
* Quand je survole un des éléments avec le curseur, celui-ci change de forme avec un picto "déplacer" - si je clique et maintien je peux déplacer l'image
Normale que tu ne le fasse pas apparaître dans tes image test ?

**Comment by haniju** [comment]
> On peut se poser aussi la question pour les dimensions des éléments.

Ça je pensais l'imposer par famille (du style bouche : 20vh ; nez : 15 ; yeux : 25 etc...) dans un premier temps - il nous faudra des feedbacks de gens qui fournissent les dessins et s’approprient le système pour savoir si on aurait besoin d'avoir plus de flexibilité, il y aurait beaucoup d'autres manières de faire !

**Comment by haniju** [comment]
>     * Quand je survole un des éléments avec le curseur, celui-ci change de forme avec un picto "déplacer" - si je clique et maintien je peux déplacer l'image
      Normale que tu ne le fasse pas apparaître dans tes image test ?

En fait j'ai un peu laché l'affaire là-dessus, je me suis dit qu'on ferait ça seulement si on se rends compte que les utilisateurs ne comprennent pas d'eux même - du coup je ne l'ai pas mis dans les images test !
