### ISSUE TITLE
Position & dragging

### ISSUE THREAD

**Issue by haniju** [animaux-du-futur/chimere#2]
Il y a un bug dans la définition des position des différents éléments.
Actuellement, quand on déplace un élément, il se remet automatiquement à top:0px & left:0px. Il faudrait qu'il puisse conserver les positions qui sont définies dans le fichier chimere.php

**Comment by edensor** [comment]
le problème vient que dans la version précédente du projet on travaillait en px.
et que dans la version chimère les éléments sont positionné avec vw et vh.
Du coup quand on sélectionne un élément ça change de façons de définir la position et ça bug.

**Comment by edensor** [comment]
J'ai tout mis en vw et vh du coup ça marche

**Comment by haniju** [comment]
Yes, parfait !
